class_attendance_project/urls.py
from django.contrib import admin
from django.urls import path, include

from rango import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),

# The above maps any URLs starting with rango/ to be handled by rango.
]

rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('teacher_register/', views.teacher_register, name='teacher_register'),
    path('student_register/', views.student_register, name='student_register'),
    path('login/', views.user_login, name='login'),
    path('create_attendance/', views.create_attendance, name='create_attendance'),
    path('teacher_home/', views.teacher_home, name='teacher_home'),
    path('student_home/', views.student_home, name='student_home'),
    path('sign_attendance/', views.sign_attendance, name='sign_attendance'),
    path('overall_attendance/', views.overall_attendance, name='overall_attendance'),
    path('check_attendance/', views.check_attendance, name='check_attendance'),
    path('base/', views.base, name='base'),
    path('about/', views.about, name='about'),
    path('logout/', views.user_logout, name='logout'),
    path('sign_successfully', views.sign_successfully, name='sign_successfully'),

]

rango/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
'''
This is the Teaecher Model, which contains five attributes. User is a foreign key to default User model. teacherID is
the primary key, which represents an unique attribute for Teacher model. Teacher name, course and emailAddress are 
non-primary key.
'''
class TeacherProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default='')
    teacherID = models.CharField(max_length=10, default='', unique=True)
    teacherName = models.CharField(max_length=128, default='')
    course = models.CharField(max_length=128, default='')
    emailAddress = models.EmailField(default='empty@emailaddress.com')

    def __str__(self):
        return self.teacherID


'''
This is the Student model, which is similar to the Teacher model. Student ID is the primary key and studentName,
emailAddress and belongingClass is the non-primary key. BelongingClass means to which class does this student belong.
This system contains three options: class1, class2 and class3. Students must choose one of them during registration.
'''
class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default='')
    studentID = models.CharField(max_length=10, default='', unique=True)
    studentName = models.CharField(max_length=128, default='')
    emailAddress = models.EmailField(default='empty@emailaddress.com')
    belongingClass = models.CharField(max_length=128, default='class1')

    def __str__(self):
        return self.studentID


'''
This is the Course Model, which should be automatically populated into database using populate_rango.py.
We have three default course in the system: IT, DB and Internet. 
'''
class CourseProfile(models.Model):
    courseID = models.CharField(default='', unique=True, max_length=128)
    courseName = models.CharField(default='', max_length=128)


'''
As you may aware, the word 'class' may have two different meanings in this system.
One is the belongingClass in Student Model. Student should choose 'Class1' 'Class2' or 'Class3'
Another represents the ClassProfile model. This model actually stored the information of ClassProfile.
When teachers generated class attendance lists. they actually generate a new entity of this model.
ClassID is a randomly generated number stored, meanwhile it is also the primary key of this model.
taecherID and courseID are two foreign keys pointing to Course model and Teacher model.
Therefore, I want to emphasize that 'class1' 'class2', and 'class3' are not the ClassID.
ClassID should be a 3 digits number like '375', '462'.....
'''
class ClassProfile(models.Model):
    classID = models.IntegerField(default=-1, unique=True)
    teacherID = models.CharField(max_length=128, default='')
    courseID = models.CharField(default='', max_length=128)
    Date = models.DateField()
    '''How many present students'''
    numOfStudents = models.IntegerField(default=0)
    belongingClass = models.CharField(max_length=128, default='class1')


'''
This is the Attendance Model. When students sign attendance, they eventually create a new entity of this model.
It contains three attributes. ClassID and studentID together to be the composite key. ClassID is the foreign key
to Class Profile and StudentID is the foreign key to student profile.
'''
class AttendanceProfile(models.Model):
    classID = models.IntegerField(default=-1)
    studentID = models.CharField(max_length=128)
    studentName = models.CharField(max_length=128)

    class Meta:
        unique_together = ("classID", "studentID")

rango/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import widgets

from rango import models
from rango.models import TeacherProfile, StudentProfile, ClassProfile

'''
This is the teacher registration form.  TeacherForm represent the teacher accounts, username and password
'''
class TeacherForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

'''
This is also the teacher registration form. It include the teacher ID, teacher name, course and email address.
'''
class TeacherProfileForm(forms.ModelForm):
    class Meta:
        model = TeacherProfile
        fields = ('teacherID', 'teacherName', 'course', 'emailAddress')

'''
This is for student registration, it contains username and password
'''
class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

'''
It contains all information about students including studentID, studentName, emailAddress and belonging class.
Belonging class mains which class is this student belong to. In this system, We have three default choice which is 
class1, class2 and class3.
'''
class StudentProfileForm(forms.ModelForm):
    select_value = (
        ('class1', 'class1'),
        ('class2', 'class2'),
        ('class3', 'class3'),
    )
    belongingClass = forms.CharField(max_length=128, help_text='Please choose your class',
                                     widget=widgets.Select(choices=select_value))

    class Meta:
        model = StudentProfile
        fields = ('studentID', 'studentName', 'emailAddress', 'belongingClass')

'''
This form is used for generating classes. It contains two information courseID and Date, where courseID is an option.
Teachers should choose One of them as the course.
'''
class ClassProfileForm(forms.ModelForm):
    select_value = (
        ('01_Information_Technology', 'Information Technology'),
        ('02_Database', 'Database'),
        ('03_Internet', 'Internet'),
    )
    value = (
        ('class1', 'class1'),
        ('class2', 'class2'),
        ('class3', 'class3'),
    )
    courseID = forms.CharField(widget=widgets.Select(choices=select_value), help_text="Please choose your course name")

    Date = forms.DateField(widget=forms.SelectDateWidget, help_text="Enter the course date")
    belongingClass = forms.CharField(
        widget=widgets.Select(choices=value), help_text="Please choose the class taking this course")

    class Meta:
        model = ClassProfile
        fields =('courseID', 'Date', 'belongingClass')

rango/views.py
import random

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from rango.forms import TeacherForm, TeacherProfileForm, StudentForm, StudentProfileForm, ClassProfileForm
from rango.models import TeacherProfile, ClassProfile, AttendanceProfile, CourseProfile, StudentProfile

'''
This is the index function
'''
def index(request):
    return render(request, 'rango/index.html', {})

'''
This is the About Us function
'''
def about(request):
    return render(request, 'rango/about.html')


'''
This is the teacher registration funtion, it will take TeacherForm and Teacher ProfileForm results and analyze them.
TeacherForm will be saved as the user information. TeacherProfileForm will be saved as the basic information for teachers
'''
def teacher_register(request):
    registered = False

    if request.method == 'POST':
        user_form = TeacherForm(request.POST)
        profile_form = TeacherProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = TeacherForm()
        profile_form = TeacherProfileForm()

    return render(request, 'rango/teacher_register.html', {'user_form': user_form,
                                                    'profile_form': profile_form,
                                                    'registered': registered})


'''
Register for students is similar to register for teachers.
StudentForm contains username and passwords; StudentProfileForm contains student basic information.
'''
def student_register(request):
    registered = False

    if request.method == 'POST':
        user_form = StudentForm(request.POST)
        profile_form = StudentProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = StudentForm()
        profile_form = StudentProfileForm()

    return render(request, 'rango/student_register.html', {'user_form': user_form,
                                                    'profile_form': profile_form,
                                                    'registered': registered})


'''
This is the function for user logging in. The Algorithm for this is:

1. get the username and password
2. check whether this account is valid
    2.1 If user account is not valid, print error information
    2.2 If user account is valid, log in to the system then:
        2.2.1   Check whether Teacher Model contains this user
            2.2.1.1 If this user is a teacher account, redirect users to 'teacher_home'
            2.2.1.2 If this user is not a student account, which means it should be a student account
                    therefore, redirect users to 'student_home'
'''
def user_login(request):
    context_dict = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            '''Check if user account is valid'''
            if user.is_active:
                login(request, user)
                '''Try to find whether this user is a teacher account'''
                try:
                    teachers = TeacherProfile.objects.get(user=user)
                    context_dict['teacher'] = teachers
                    '''If not then is is a student account'''
                except TeacherProfile.DoesNotExist:
                    teachers = None
                    student = StudentProfile.objects.get(user=user)
                    context_dict['student'] = student
                if teachers is not None:
                    return redirect(reverse('rango:teacher_home'))
                else:
                    return redirect(reverse('rango:student_home'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html', {})

'''
This is the logout method
'''
def user_logout(request):
    logout(request)
    return render(request, 'rango/logout.html', {})

'''
This is the teacher_home method, it detects the users' teacher ID and name, which will be used on front ends.
'''
def teacher_home(request):
    context_dict={}
    if request.user.is_authenticated:
        teacher = TeacherProfile.objects.get(user=request.user)
        context_dict['teacher'] = teacher
        return render(request, 'rango/teacher_home.html', context=context_dict)
    return render(request, 'rango/teacher_home.html', context=context_dict)


'''
Here shows the algorithm of create the attendance lists:
1. Set classes as all class objects in Class model, 
    set teacher to all teacher objects in Teacher Model
2. Get the courseID, Date and belongingClass in ClassProfileForm on front ends.
3. Start to generate a random number to represent Class ID, which must be unique in Class model in database:
    3.1 generate an loop stop checker called out = False.
    3.2 While out is False:
        3.2.1 set out to True
        3.2.2 generate a random number from 0 to 999, called cid
        3.2.3 for all classes, check whether their class IDs are the same with cid:
            3.2.3.1 If they have the same ID, change set = False
4.  Save the Class ID and set the default numOfStudents = 0
5.  Save the new class entity
'''
def create_attendance(request):
    context_dict = {}
    classes = ClassProfile.objects.all()
    finish = False
    teacher = ''
    if request.user.is_authenticated:
        teacher = TeacherProfile.objects.get(user=request.user)
        context_dict['teacher'] = teacher
    if request.method == 'POST':
        class_form = ClassProfileForm(request.POST)
        if class_form.is_valid():
            new_class = class_form.save(commit=False)
            out = False
            cid = 0
            while out is not True:
                out = True
                cid = random.randint(0, 999)
                for c in classes:
                    if c.classID == cid:
                        out = False
            new_class.teacherID = teacher.teacherID
            new_class.classID = cid
            new_class.numOfStudents = 0
            context_dict['cid'] = cid
            new_class.save()
            finish = True
            context_dict['finish'] = finish
            return render(request, 'rango/create_attendance.html', context=context_dict)
        else:
            print(class_form.errors)
    else:
        class_form = ClassProfileForm(request.POST)
        context_dict['class_form'] = class_form
    context_dict['finish'] = finish
    return render(request, 'rango/create_attendance.html', context=context_dict)


'''
Student Home need to search right classes to sign attendance, The algorithm for this is shown below:
1. check the account information. get the student ID and student name.
2.  get the class ID students input from front ends.
3. Check if this class ID is valid:
    3.1 If this class ID is valid, compare whether they have the same belongingClass:
        3.1.1 if they have the same belongingClass attributes, it means this student belongs to this class
            therefore he can sign the attendance.
            3.1.1.1 get all class information together with this students' information send them to the sign_attendance page
        3.1.2 If they have different belongingClass attributes, this student can not sign the attendances, print errors.
    3.2 If this class ID is not valid, print errors
'''
def student_home(request):
    context_dict = {}
    if request.method == 'POST':
        classid = request.POST.get('classid')
        context_dict['classid'] = classid
        if request.user.is_authenticated:
            student = StudentProfile.objects.get(user=request.user)
            studentid = student.studentID
            studentname = student.studentName
            context_dict['studentid'] = studentid
            context_dict['studentname'] = studentname
            try:
                this_class = ClassProfile.objects.get(classID=classid)
                if this_class.belongingClass == student.belongingClass:
                    courseID = this_class.courseID
                    this_course = CourseProfile.objects.get(courseID=courseID)
                    courseName = this_course.courseName
                    teacherid = this_class.teacherID
                    course_date = this_class.Date
                    date = str(course_date)
                    context_dict['classname'] = courseName
                    context_dict['teacherid'] = teacherid
                    context_dict['date'] = date
                    return render(request, 'rango/sign_attendance.html', context=context_dict)
                else:
                    context_dict['wrongclass'] = True
                    return render(request, 'rango/student_home.html', context=context_dict)
            except ClassProfile.DoesNotExist:
                context_dict['not_found'] = True
                context_dict['does_not_exist'] = 'Your Class ID Does Not Exist'
                return render(request, 'rango/student_home.html', context=context_dict)

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no">
    <!-- all title should start with class_attendance_ -->
    <title>
        class_attendance_
        {% block title_block %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- this is the css and js for bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <script src="{% static 'js/base.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body  class="base_body">
<div class="main">
<!-- navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <!--this is my web icon-->
    <img src="{% static 'images/attendance2.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    Class Attendance
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <!--link to index page-->
      <li class="nav-item active">
        <a class="nav-link red_link" href="{% url 'rango:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        <!--link to about us-->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'rango:about' %}">About Us</a>
      </li>
        <!--if user logged in, allow they to log out-->
      {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:logout' %}">Logout</a>
        </li>
        {% else %}
        <!--if they did not log in, let them register-->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:teacher_register' %}">Teacher Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:student_register' %}">Student Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:login' %}">Login</a>
          </li>
        {% endif %}
    </ul>
  </div>
</nav>

{% block main_block %}
<!-- Main Content of Page, all other page source are inside body_block -->
<div class="left_block center">
    {% block body_block %}
    {% endblock %}
</div>
{% endblock %}


{% block carousel_block %}
<!-- Image Carousel -->
<div class="right_block">
     <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{% static 'images/attendance1.png' %}" class="d-block w-100" alt="attendance1">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/attendance3.png' %}" class="d-block w-100" alt="attendance3">
                </div>
                <div class="carousel-item">
                  <img src="{% static 'images/attendance4.png' %}" class="d-block w-100" alt="attendance4">
                </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
          </a>
    </div>
</div>

{% endblock %}
</div>
</body>
</html>

templates/rango/check_attendance.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    check_attendance
{% endblock %}


{% block body_block %}
<form id="attendance_form" method="post" action="{% url 'rango:check_attendance' %}">
    {% csrf_token %}
    {% csrf_token %}
    Input the class ID: <input type="text" name="classid"><br>
    Choose the class taking this course:
        <select name="belonging_class">
            <option value="class1">class1</option>
            <option value="class2">class2</option>
            <option value="class3">class3</option>
        </select><br>
    <input type="submit" value="Search"><br>
</form>
    <h3> Students in class</h3>
    <table class="table">
        <thead class="thead-dark table-striped">
            <tr>
                <th>studentID</th>
                <th>studentName</th>
            </tr>
        </thead>
        {% for student in in_class %}
        <tr>
            <td>{{ student.studentID }}</td>
            <td> {{ student.studentName}}</td>
        </tr>
        {% endfor %}
    </table>
    <h3> Absent Students</h3>
    <table class="table table-striped">
        <thead class="thead-light">
            <tr>
                <th>studentID</th>
                <th>studentName</th>
            </tr>
        </thead>
        {% for student in absent %}
        <tr>
            <td>{{ student.studentID }}</td>
            <td> {{ student.studentName}}</td>
        </tr>
        {% endfor %}
    </table>
    <h3><a class="red_link" href="{% url 'rango:teacher_home' %}" >Back to teacher home</a></h3>
{% endblock %}

templates/rango/create_attendance.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    create_attendance
{% endblock %}


{% block body_block %}
{% if not finish %}
<h1>This is attendance creation page</h1>
    <div>
        <form id="class_form" method="post" action="{% url 'rango:create_attendance' %}">
            {% csrf_token %}
            {% csrf_token %}
            {% for hidden in class_form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in class_form.visible_fields %}
                {{ field.help_text }}
                {{ field }}
                <br><br>
            {% endfor %}
            <input type="submit" name="submit" value="Create Attendance" />
        </form>
    </div>
Submit this form to generate class attendance.
{% else %}
<h1 class="center_one"> Your ClassID is {{cid}}</h1><br>
<h5> Now your students can use this ClassID to sign in!</h5><br>
<h3><a href="{% url 'rango:teacher_home' %}">Return to teacher home</a></h3>
{% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    index
{% endblock %}

<!--
    This is the html file for index page. Index page has two different layout decided by the screen size,
    if the size is less then 768px, it will not show the picture.
    class h_block: will be disappear when use computer.
    class hidden_block: will be disappear when use mobile phone.
-->
{% block body_block %}
<div class="container deff center">
    <!--This is a mobile layout-->
    <div class="center h_block top_one"><h5>Class Attendance System</h5></div>
    <!--This is a mobile layout-->
    <div class="center h_block">Attend Today, Achieve Tomorrow</div>
    <!--This is a computer layout-->
    <h3 class="hidden_block">Welcome to class attendance system </h3><br>
    <!--This is a mobile layout-->
    <div class="h_block center">
        <img src="{% static 'images/attendance2.png' %}" class="d-inline-block mobile_icon" alt=""></div>
    <h5 class="hidden_block center">
        <p  class="serif"> When students improve their attendance rates, they improve their academic prospects and chances for graduating.</p>
            <small>-- Former U.S. Secretary of Education<cite title="Source Title"> Arne Duncan</cite></small>
        </blockquote>
    </h5>
    <div class="center">
        <button type="button" class="my_button">
            <a class="red_link" href="/rango/about/">About</a>
        </button>&nbsp&nbsp

        <!--When user is authenticated, show logout-->
        {% if user.is_authenticated %}
            Hello {{user.username }} Welcome to Class Attendance System 😀.
        <button type="button" class="my_button">
            <a href="{% url 'rango:logout' %}"> logout </a>
        </button>&nbsp&nbsp
        <!--else show the registration and login-->
        {% else %}
            <button type="button" class="my_button">
                <a class="red_link" href="{% url 'rango:login' %}">Login</a>
            </button>&nbsp&nbsp
            <button type="button" class="my_button">
                <a class="red_link" href="{% url 'rango:teacher_register' %}">Teacher Register</a>
            </button>&nbsp&nbsp
            <button type="button" class="my_button">
                <a class="red_link" href="{% url 'rango:student_register' %}">Student Register</a>
            </button>&nbsp&nbsp
        {% endif %}
    </div>
</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    login
{% endblock %}

<!--This is the log in page. It will take the user name and accounts and send them to the login function in views.py-->
{% block body_block %}
    <h1>Login Page</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}"><br><br>
    {% csrf_token %}
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="20%" /><br><br>
    <br />
    Password: <input type="password" name="password" value="" size="20%" /><br><br>
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/student_register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    student_register
{% endblock %}

<!--This is the student registration page-->
{% block body_block %}
    <h1>Register for Student</h1>
    {% if registered %}
        <Strong>Thank you for registrations!</Strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        <Strong>Register Here!</Strong>
<!--submit two different form: StudentForm and StudentProfileForm-->
        <form id="user_form" method="post" action="{% url 'rango:student_register' %}"
              enctype="multipart/form-data">

            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
    <img style="height: 100px" src="{% static 'images/thank you.png' %}" alt="picture" />
{% endblock %}

templates/rango/teacher_home.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    teacher_home
{% endblock %}

<!--
    Teacher Home is also an instruction page for teachers.
    By clicking different hyper-links in this page, they will be redirected to different pages.
-->
{% block body_block %}
<h1>Teacher Home</h1>
<h3> Hello teacher {{user.username}}, teacher ID: {{teacher.teacherID}}.</h3>
<div class="container">
    <!--This link can be used to create attendance sheets-->
    <a class="red_link" href="{% url 'rango:create_attendance' %}">
        <img style="height: 150px" src="{% static 'images/dianming.jpg' %}" alt="roll call">
        Create Class Attendance sheets
    </a><br>
    <!--This link can be used to check overall attendance rates table-->
    <a class="red_link" href="{% url 'rango:overall_attendance' %}">
        <img style="height: 150px" src="{% static 'images/overall_attendance.jpg' %}" alt="roll call">
        Overall Attendance Condition
    </a><br>
    <!--This link can be used to check the absent students -->
    <a class="red_link" href="{% url 'rango:check_attendance' %}">
        <img style="height: 150px" src="{% static 'images/absent_students.jpg' %}" alt="roll call">
        Check Who is Missing
    </a><br>
</div>
{% endblock %}

templates/rango/teacher_register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    teacher_register
{% endblock %}

<!--This is the teacher registration page-->
{% block body_block %}
    <h1>Register for Teacher</h1>
    {% if registered %}
        <Strong>Thank you for registrations!</Strong>
        <a href="{% url 'rango:index' %}">Go to Login!.</a><br />
    {% else %}
        <Strong>Register Here!</Strong>
<!--submit two different form: TeacherForm and TeacherProfileForm-->
        <form id="user_form" method="post" action="{% url 'rango:teacher_register' %}"
              enctype="multipart/form-data">

            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
    <img style="height: 100px" src="{% static 'images/thank you.png' %}" alt="picture" />
{% endblock %}